language: ruby
rvm:
- 2.0.0

script:
- bundle exec compass compile
- bundle exec jekyll build

after_success:
- "./_scripts/travis_deploy.sh"

#white list 
branches:
only:
  - master
  - live
  - gh-pages # test the gh-pages branch
