language: ruby
rvm:
- 2.0.0


install:
- bundle install
script: bundle exec rake

after_success:
- "./_scripts/travis_deploy.sh"

#white list 
#branches:
#only:
  #- master
  #- live
  #- gh-pages # test the gh-pages branch
